node_color_map:
  place: '#1f77b4'
  person: '#aec7e8'
  organization: '#ff7f0e'
  position: '#ffbb78'
  concept: '#2ca02c'
  program: '#98df8a'
  technology: '#d62728'
  '': '#ff9896'
  group: '#9467bd'
  event: '#c5b0d5'
  publication: '#8c564b'
  postion: '#c49c94'
  date: '#e377c2'
  object: '#7f7f7f'


gravis_plot_config:
  graph_height: 900
  use_node_size_normalization: True
  node_hover_neighborhood: True
  node_drag_fix: True
  node_size_normalization_max: 12
  node_size_factor: 1.8
  node_label_size_factor: 0.55
  use_edge_size_normalization: False
  edge_label_size_factor: 0.5
  node_label_data_source: label
  edge_label_data_source: label
  edge_curvature: 0.12
  show_edge_label: True
  use_collision_force: False
  links_force_distance: 72
  use_y_positioning_force: False
  y_positioning_force_strength: 0.05
  use_many_body_force_min_distance: True
  many_body_force_min_distance: 100
  many_body_force_strength: -372
  use_many_body_force_max_distance: True
  many_body_force_max_distance: 1200
  node_hover_tooltip: True
  