node_color_map:
  place: '#1f77b4'
  person: '#aec7e8'
  organization: '#ff7f0e'
  position: '#ffbb78'
  concept: '#2ca02c'
  program: '#98df8a'
  technology: '#d62728'
  '': '#ff9896'
  group: '#9467bd'
  event: '#c5b0d5'
  publication: '#8c564b'
  postion: '#c49c94'
  date: '#e377c2'
  object: '#7f7f7f'